version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.4.0
  aws-ecs: circleci/aws-ecs@0.0.11

jobs:
  build_and_deploy:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup common environment variables
          command: |
            echo 'export ECR_REPOSITORY_NAME="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV

            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
              echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:latest-qa"' >> $BASH_ENV
            elif [ "${CIRCLE_BRANCH}" == "release" ]
            then
              echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:latest-prod"' >> $BASH_ENV
            fi
      - run:
          name: Install dependencies for project
          command: gradle assemble
      - run:
          name: Install dependencies for AWS
          command: |
            sudo apt-get update
            sudo apt-get -y -qq install awscli
            sudo apt-get install python3-pip
            sudo pip3 install --upgrade awscli
      - run:
          name: Build image
          command: |
            docker build -t $FULL_IMAGE_NAME .
      - run:
          name: Push image
          command: |
            eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            docker push $FULL_IMAGE_NAME
  update:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run:
          name: Install dependencies for AWS
          command: |
            sudo apt-get update
            sudo apt-get -y -qq install awscli
            sudo apt-get install python3-pip
            sudo pip3 install --upgrade awscli
      - run:
          name: Force Update Existing Service
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
               aws ecs update-service --cluster qa-ecs-cluster --service search-ecs-service-qa --force-new-deployment
            elif [ "${CIRCLE_BRANCH}" == "release" ]
            then
              aws ecs update-service --cluster prod-ecs-cluster --service search-ecs-service-prod --force-new-deployment
            fi

workflows:
  build-deploy-qa:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master
      - update:
          requires:
            - build_and_deploy
          filters:
            branches:
              only: master
  build-deploy-prod:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: release
      - update:
          requires:
            - build_and_deploy
          filters:
            branches:
              only: release
